spring:
  application:
    name: copilot-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-frvjdwj3fq0gwfb7.us.auth0.com/

auth0:
  domain: <DMAIN>>
  m2m:
    client-id: <CLIENTID>
    client-secret: <SECRET>

server:
  port: 8080

llm:
  api:
    key: <KEY>
  model: gpt-4o-mini

logging:
  level:
    org.springframework.security: DEBUG